version: '3.9'

services:
  web-django:
    image: remoteworker.id/equin-django-docker
    container_name: equin-django-container
    build: .
    volumes:
      - .:/equin-django-docker
    ports:
    - "8080:8080"
    command: python3 manage.py runserver 0.0.0.0:8080

  db-postgres:
    image: library/postgres:13
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"


volumes:
  postgres_data:
